homeassistant:
  name: Home
  latitude: !secret latitude 
  longitude: !secret longitude
  elevation: 179  
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  server_host: 127.0.0.1

recorder:
  db_url: !secret db_url
  purge_days: 7
  exclude:
    entities:
      - sensor.weather_apparent_temperature
      - sensor.weather_humidity
      - sensor.weather_icon
      - sensor.weather_precip_intensity
      - sensor.weather_precip_probability
      - sensor.weather_summary
      - sensor.weather_temperature
      - sensor.weather_hourly_summary
      - sensor.weather_daily_summary
      - sensor.weather_wind_speed
      - sun.sun 
  
history:  
# Enables the frontend
frontend:
updater:
config:
# Discover some devices automatically
discovery:

# View all events in a logbook
logbook:

emulated_hue:
  expose_by_default: true

tts: 
  - platform: google

octoprint:
  host: 192.168.1.111
  api_key: !secret octoprint 

logger:
  default: error
  logs:
    homeassistant.components.automation: info
    #homeassistant.components.switch.flux: info

notify:
  - name: simplepush
    platform: simplepush
    device_key: !secret simplepushkey


google:
  client_id: !secret googleclientid
  client_secret: !secret googleclientsecret
###########################
# VIEWS
###########################

group:
  default_view:
    view: yes
    entities:
      - group.all_lights
      - media_player.raptor
      - group.system
      - group.weather
      - group.internet
      - media_player.google_play__blackbox
      - group.all_automations
      - switch.wake_on_lan
  living_room:
    name: Living Room
    view: yes 
    entities: 
      - group.livingroom_lights
      - media_player.raptor
      - automation.living_room_lights_on_at_sunset
      - automation.living_room_lights_on
  office:
    name: Office
    view: yes
    entities:
      - light.officebotfloor
      - light.officebot
      - group.internet
      - group.weather
      - group.ship
      - media_player.google_play__blackbox
      - group.all_devices
      - switch.wake_on_lan
      - switch.fluxer
      - automation.fluxer_switch_on_by_default
      - automation.office_lights_motion_off
      - automation.office_lights_motion_on
      - group.all_scripts
      - calendar.appointments_private
  bedroom:
    name: Bedroom
    view: yes
    entities:
      - light.sleepbot
      - group.weather
  kitchen: 
    name: Kitchen
    view: yes
    entities: 
      - light.kitchen
      - automation.kitchen_light_on_at_sunset     
  printer:
    name: 3D
    view: yes
    entities: 
      - group.3d_print

  
###########################
# GROUPS
###########################    
  Internet: sensor.speedtest_download, sensor.speedtest_upload, sensor.speedtest_ping
  Weather: sensor.weather_apparent_temperature, sensor.weather_humidity, sensor.weather_icon, sensor.weather_precip_intensity, sensor.weather_precip_probability, sensor.weather_summary, sensor.weather_temperature, sensor.weather_hourly_summary, sensor.weather_daily_summary, sensor.weather_wind_speed, sun.sun
  System: sensor.cpu_use, sensor.ram_free, sensor.ram_use, sensor.load_5m, sensor.load_5m, sensor.memory_use, sensor.memory_free, sensor.disk_free
  Ship: sensor.packages
  livingroom_lights: light.tribot, light.couchbot 
  office_lights: light.officebot, light.officebotfloor
  3D_print: sensor.octoprint_actual_bed_temp, sensor.octoprint_actual_tool0_temp, sensor.octoprint_current_state, sensor.octoprint_job_percentage, sensor.octoprint_target_bed_temp, sensor.octoprint_target_tool0_temp



switch 2:
  - platform: wake_on_lan
    mac_address: "D8-CB-8A-E2-03-A2"
    host: 192.168.1.114


################################################################          
# Sensors/Components
################################################################


light:
  - platform: lifx
    broadcast: 192.168.1.255
  
# Google Play Music - Brian Desktop
media_player 2:
  platform: gpmdp
  host: 192.168.1.114
  name: Google Play - Blackbox

media_player 3:
  platform: cast
  
# Track the sun
sun:

sensor 6:
  - platform: template
    sensors: 
      new_commits:
        value_template: >
          {{ states("sensor.new_commits") }}

################################
# Z-WAVE #######################
################################
zwave:
  usb_path: /dev/zwave


###############################
# Device Tracker
###############################

device_tracker:
  - platform: owntracks
  - platform: tplink
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password 
    interval_seconds: 10
    consider_home: 180
    track_new_devices: no


#########################################
# MQTT
##########################################

mqtt:
  broker: !secret mqttbroker
  port: 19742
  username: !secret mqttuser
  password: !secret mqttpassword

################################################################
# Panels
################################################################
# These are broken due to HTTP loading on HTTPS connection.
panel_iframe:
  router:
    title: 'Router'
    icon: mdi:router-wireless
    url: 'http://192.168.1.1'
  modem:
    title: 'Modem Admin'
    icon: mdi:router-wireless
    url: 'http://192.168.100.1'
  graph:
    title: Graph
    icon: mdi:vector-polyline
    url: "https://raptorbot.ddns.net/local/graph.html"
################################################################          
# Includes
################################################################
automation: !include automation.yaml
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
script: !include_dir_named script/
shell_command: !include_dir_named shell_command/
